# create_gitignore.ps1
# PURPOSE: Creates the .gitignore file in the repo root
# WHY A SCRIPT: .gitignore is a hidden file that browsers sometimes mangle on download
# HOW TO RUN (from socialspace repo root):
#   .\docs\create_gitignore.ps1

$root = "C:\Users\dheer\Downloads\socialspace-workspace\socialspace"
$path = "$root\.gitignore"

$content = @"
# Python
__pycache__/
*.pyc
*.pyo
*.pyd
venv/
env/
.venv/
.pytest_cache/
*.egg-info/
dist/
build/
*.egg

# Node / Frontend
node_modules/
.vite/
dist/
build/
.cache/
*.local

# Environment files — NEVER commit these, they contain secrets
.env
.env.local
.env.development
.env.production
.env.*.local

# IDE
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
desktop.ini

# Logs
*.log
npm-debug.log*

# Auto-generated verification output — large, regenerated by script
docs/VERIFICATION_OUTPUT.txt
docs/HANDOFF_BACKUP.md
docs/SESSION_END_OUTPUT.txt
"@

Set-Content -Path $path -Value $content -Encoding UTF8
Write-Host ".gitignore created at: $path"
Write-Host ""
Write-Host "Now run these commands to make your first safe git commit:"
Write-Host "  cd $root"
Write-Host "  git add .gitignore"
Write-Host "  git commit -m `"add gitignore`""
Write-Host "  git add -A"
Write-Host "  git commit -m `"initial project snapshot`""
